import numpy as np
import matplotlib.pyplot as plt

'''Start'''
'''The below function does the filtering of the '''


def filter_tx(d,usf_filter,switch_graph):
    usf_filter =8

# Upsampling such that original symbols are at every usf_filter th place
    Upsampled_signal = np.zeros(len(d)*usf_filter,dtype=complex)
    Upsampled_signal[::usf_filter]=d

# Ideal low pass filter is rectangular filter in frequency domain and sinc in time domain
    cut_off = 1/ (2 * usf_filter)
    t=np.arange(-50,51)
    ideal_LPFilter = np.sinc(2 * cut_off * t)
    ideal_LPFilter = ideal_LPFilter / np.sum(ideal_LPFilter)
    plt.figure(figsize=(6,6))
    plt.plot(t,ideal_LPFilter)
    plt.grid(True)
    plt.show()


# Filtered signal generated by convolution with sinc
    filtered_signal = np.convolve(Upsampled_signal,ideal_LPFilter, mode='full')
    print(f'Filtered Signal:{filtered_signal} ')

    if switch_graph.upper() == 'ON':
        plt.figure(figsize=(10, 6))
        plt.plot(np.real(filtered_signal), label='Real part')
        plt.plot(np.imag(filtered_signal), label='Imaginary part')
        plt.title("Filtered Signal (Low-pass Filter)")
        plt.xlabel("Sample Index")
        plt.ylabel("Amplitude")
        plt.legend()
        plt.grid(True)
        plt.show()
    else:
        pass

    return filtered_signal